version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install -DskipTests -Ddremio.oss-only=true -Dlicense.skip=true -Dcheckstyle.skip -e
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
         root: ./
         paths:
           - target/
      - run: ls -al target/

workflows:
  version: 2

  build-then:
    jobs:
      - build
